# Generated by Django 4.0.2 on 2022-03-21 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schoolbudget', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pupils',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.DateField()),
                ('amount', models.IntegerField()),
                ('grade', models.IntegerField()),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schoolbudget.school')),
            ],
            options={
                'unique_together': {('school', 'semester', 'grade')},
            },
        ),
    ]
