# Generated by Django 4.0.2 on 2022-03-30 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolbudget', '0002_pupils'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pupils',
            old_name='amount',
            new_name='autumn',
        ),
        migrations.RenameField(
            model_name='pupils',
            old_name='semester',
            new_name='year',
        ),
        migrations.AlterUniqueTogether(
            name='pupils',
            unique_together={('school', 'year', 'grade')},
        ),
        migrations.AddField(
            model_name='pupils',
            name='spring',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
