# Generated by Django 4.0.2 on 2022-04-24 04:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schoolbudget', '0003_rename_amount_pupils_autumn_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='schoolSimiliar',
            field=models.ManyToManyField(blank=True, to='schoolbudget.School'),
        ),
        migrations.AlterUniqueTogether(
            name='school',
            unique_together={('responsibility', 'name')},
        ),
        migrations.CreateModel(
            name='BudgetPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('amount', models.FloatField()),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schoolbudget.school')),
            ],
            options={
                'unique_together': {('school', 'date')},
            },
        ),
    ]
