# Generated by Django 4.0.2 on 2022-03-24 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extenduser',
            name='city',
        ),
        migrations.AddField(
            model_name='extenduser',
            name='schoolID',
            field=models.IntegerField(default=0),
        ),
    ]
