# Generated by Django 4.0.2 on 2022-03-28 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_extenduser_city_extenduser_schoolid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='extenduser',
            old_name='r',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='extenduser',
            name='user_type',
            field=models.DateField(default='principal', null=True),
        ),
    ]
