# Generated by Django 4.0.2 on 2022-03-28 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_r_extenduser_user_alter_extenduser_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extenduser',
            name='user_type',
            field=models.CharField(default='principal', max_length=30, null=True),
        ),
    ]
