# Generated by Django 4.0.2 on 2022-05-02 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_extenduser_schoolid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extenduser',
            name='schoolID',
            field=models.IntegerField(default=11010, null=True),
        ),
    ]
